name: Build Docs
on:
  push:
    branches:
      - docs
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: redkubes/docusaurus-deploy-action@v1
        with:
          source-folder: './'
          git-user: mhnpd
          git-password: ${{ secrets.SECRET }}
          deployment-branch: gh-pages